version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_KEY_CLOACK_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${DB_KEY_CLOACK_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${DB_KEY_CLOACK_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:${PORT}
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL}
      - PRODUCT_SERVICE_PORT=${PRODUCT_SERVICE_PORT}
      - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
      - ORDER_SERVICE_PORT=${ORDER_SERVICE_PORT}
